# A stress test for pathfinding 


map: |
    +-------------------------------------+
    |@|  M                                |
    |T|---------------------------------- |
    | |                                   |
    | | ----------------------------------|
    | |                                   |
      |---------------------------------- |
      |  M                                |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |   M M M M M M M  M                |
      | ----------------------------------|
      |   M                               |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                   |
      |---------------------------------- |
      |                                   |
      | ----------------------------------|
      |                                  w|
      +-----------------------------------+

objects:
    M:
       name: Old Man
       group: NPCs
       visible: True
       color: green
       attributes:
            health: -1  # Infinite health
            defense: -1  # Unhurtable
            speed: 1
    w:

        name: Old Man Waypoint
        group: Waypoints
        visible: False
triggers:
    T:
        - action: walk
          actor: Old Man
          target: Old Man Waypoint
          speed: 1
