# Tutorial level for Cellar Strider

map: |
    +----------------------+--------------------------+
    |       W              |                          |
    |   @   W       M      |                          |
    |      WW              |            F             |
    |WWWWWWW               |                          |
    |                      |        GGGGGGGGGGGGGGGGGG|
    +---------+TTTTT+------+      GGG                 |
    |                      |GGGGGGG                   |
    |   S                  |                          |
    |                   S  +                          |
    |           S                                     |
    |                                                 |
    +-------------------------------------------------+

# @ is player, M is "old man" tutor-guy
# T triggers S, which are spawners to spawn nonmoving tutorial mobs
# W triggers the old man, who gives the player a training sword and
# then walks into the next room

objects:
    M:
       name: Old Man
       group: NPCs
       visible: True
       color: green
    S:
        name: Spawner
        group: Spawners
        visible: False
    F:
        name: Old Man Waypoint
        group: Waypoints
        visible: False
    D:
        name: Training enemy
        group: Training enemies
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 5
              damage: 5
        attributes:
            health: 10

triggers:
    W:
        - action: script
          script:
            - Old Man: Woah there, youngun!
            - Old Man: I can't let you go out there without some training, can I?
            - Old Man: Here, take this! It ain't much more than a stick, but it'll do the basics.
        - action: give
          actor: Old Man
          item: Training sword
          type: weapon
          attributes:
              damage: 5
        - action: script
          script:
            - Old Man: Don't just stand there staring at it! Open up the equip menu with "i", and put it on! 
        - action: walk
          actor: Old Man
          target: Old Man Waypoint
          speed: 4
    T:
        - action: script
          script:
            - Old Man: Here come some enemies!
            - Old Man: Don't worry, they're just practice dummies.
            - Old Man: Do you really think I'd send you into combat with only a training sword?
        - action: spawn
          actor: group(Spawners)
          target: D
    G:
        - action: script
          script:
            - Old Man: Good job, whipersnapper!
            - Old Man: Now go on an adventure, you're all ready!
        - action: end game
