# main-game level 2

map: |
    1                               +--------------------------------------------------------------------+----+
                                   /             x          hhhhh|        \             /    /     /     |     \
                                  +                         \    |   \     \           /33| /  \  /  \   |  /   \
                                  \    S                     +   |    \     \         / c \     \     \    /     \
                               +---+                    x    |   |     \ w   \       /----/   +-----------+  w    \
           +-------+           |  N=                         |ggg|      \     +-----+                      \       +
          /         \          +---+                         +   |  w    \                                  \     /
         +          a\            /       x                   \           \                                  |fff/
         |         aa +-------------------------------------------------------------------------------+      |  +
         |    +---+a       d   u                 u                   u                 u               \    u|   \
         /   /    |         d          u                    u                         u                 \    |    \
        /   /     |      +-------+---------------+---------------------------------------------------+   \   |     +
    +--+jjj/      |             /                 \             |                 \      v            \   \  +     |
    |     /       |            /  /+---------+     \   +-----+  /  +----+-------+  \                   \   \       |
    | @  /        |     s     /  //           \     \       /  /   |   / \    |  \  +             T     +   +      |
    +---+         +          /  //  /\         \     \     /          /    /      |ii                   |   |      |
                   \        /      /  \      s  \     \   +--------------------+ee+   +                 |  u|      +
                    \      +------+              \     \   t                  /    \ / \  v           v |   |     /
                     \      \        +------------+     |     +---------+    /      +   +---------------+   |    /
                      \      \                   /     /      |        /    /          /               /    +   /
                       \      \     +----+      /     /          /    /    /------+   /    +------    /        /
                        \      \   /  1c1|     /   s /     +----+    /    /   t  /   /    / c2       /    +---+
                         \      \ /   111|    /     /     /         /    /    / /   /    /222       /    /w u /
                          \      +       |   /     /     /   s     /    /    /     /    /          /    / xw /
                           \      \     /   /     +-----+         /    /    +-----+    /          /      xu /
                            \   s  \   /   /                     / t  /               /          /---------+
                             \      \ / s /       +-------------+    +---------------+     t    /
                              \          /            b                                        /
                               +--------------------------------------------------------------+

objects:
    B: #Miniboss
        name: Mini-Boss
        group: Mini-Bosses
        visible: True
        color: red
        start:
            - action: script
              script:
                - Boss: Who dares enter my lair?
                - Boss: Ah, a defenseless traveler?
                - Boss: I shall destroy you!
            - action: attack
              target: Player
              speed: 1
              damage: 20
        die:
            - action: script
              script:
                - Boss: Gah! That's enough.
                - Boss: Here, take this orange.
                - Boss: Now leave me alone!
            - action: give
              item: An Orange
              type: weapon
              attributes:
                   damage: 40
            - action: script
              script:
                - You: An orange?
                - ???: An orange!
                - ???: The most powerful weapon in the free world!
                - ???: The gods must smile upon you, O strange one!
                - You: Ugh. I don't think he had the key.
        attributes:
            health: 50

    M: # boss
        name: Boss
        group: Bosses
        visible: True
        color: red
        start:
            - action: script
              script:
                - Boss: Hah! Finally!
                - Boss: I have been stuck in this damp cellar for eons.
                - Boss: Do you know know hard it is to get my goblin minions to bring me food?
                - Boss: They just don't listen, nope.
                - Boss: I would much rather have my food come to me instead!
                - Boss: Prepare to die, human!
            - action: attack
              target: Player
              speed: 2
              damage: 40
        die:
            - action: script
              script:
                - Boss: You've fought well, human.
                - Boss: Take this magical exit key. The door's to your left.
            - action: give
              item: Magical Exit Key
              type: key
              attributes:
                  unlock: Exit Door
            - action: script
              script:
                - You: Well, that was... anticlimactic.
        attributes:
            health: 200

    c: #chest
        name: Chest
        group: Chests
        visible: True
        color: yellow

    s: #enemy spawner
        name: Goblin Spawner S
        group: Goblin Spawners
        visible: False

    t: #enemy spawner
        name: Goblin Spawner T
        group: Goblin Spawners
        visible: False
    
    u: #enemy spawner
        name: Goblin Spawner U
        group: Goblin Spawners
        visible: False
    
    v: #enemy spawner
        name: Goblin Spawner V
        group: Goblin Spawners
        visible: False

    w: #enemy spawner
        name: Goblin Spawner W
        group: Goblin Spawners
        visible: False

    x: #enemy spawner
        name: Goblin Spawner X
        group: Goblin Spawners
        visible: False

    k: # goblin
        name: Goblin
        group: Goblins
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 3
              damage: 5
        attributes:
            health: 15

    S: # Boss spawner
        name: Boss Spawner
        group: Boss Spawners
        visible: False

    T: #Miniboss spawner
        name: Mini-Boss Spawner
        group: Mini-Boss Spawners
        visible: False

    =:
        name: Exit Door
        group: Doors
        visible: True
        color: magenta


triggers:
    j:
        - action: script
          script:
            - You: Wait, where am I?
            - You: This isn't my house!
    
    "1": #chest 1
        - action: give
          actor: The chest
          item: Super Health Potion
          type: potion
          attributes:
               health: 50

    "2": #chest 2
        - action: give
          actor: The chest
          item: Iron Sword
          type: weapon
          attributes:
               damage: 15

    "3": #chest 3
        - action: give
          actor: The chest
          item: Some Strange Mixture
          type: potion
          attributes:
               health: 50

    a: #enemy trigger
        - action: spawn
          actor: Goblin Spawner S
          target: k 

    b: #enemy trigger
        - action: spawn
          actor: Goblin Spawner T
          target: k 

    d: #enemy trigger
        - action: spawn
          actor: Goblin Spawner U
          target: k 

    e: #enemy trigger
        - action: spawn
          actor: Goblin Spawner V
          target: k 
    
    f: #enemy trigger
        - action: spawn
          actor: Goblin Spawner W
          target: k 

    g: #enemy trigger
        - action: spawn
          actor: Goblin Spawner X
          target: k
        - action: script
          script:
            - You: Strange...
            - You: Is that a rumbling noise I hear?

    h: # boss trigger
        - action: script
          script:
            - You: Oh no...
        - action: spawn
          actor: Boss Spawner
          target: M

    i: # miniboss trigger
        - action: spawn
          actor: Mini-Boss Spawner
          target: B

    N: # next level
        - action: load level
          level: level03
