# level 3

map: |
    +-------------------+
    |                   |
    +--   -       -     +
    |@T                /
    +--    -          + 
    |                 |
    |        -        |
    +    -            |
     \           -    |
      \               |
       +--------------+


triggers:
    T:
        - action: script
          script:
            - Strange Voice: I can't believe it.
            - Strange Voice: You actually won.
            - Strange Voice: I really didn't believe in you. At all.
            - Strange Voice: Even now, I'm shocked.
            - Strange Voice: I'll have you know I lost ten grand on this.
            - Strange Voice: I hope you're happy with yourself.
            - Strange Voice: Now the game is over.
            - Strange Voice: You don't have to go through the torment of playing it any longer.
            - Strange Voice: Really.
            - Strange Voice: You're free.
            - Strange Voice: Now go away.
        - action: end game
