# level 1 of main game

map: |
    +-----------------------------------+
    |    H                  A           |
    |   @H                  Ap          |
    |   H                   A           |
    +------------------------+       +--+
    |                                   |
    |                                   |
    +-------+-----+     +--+     +------+
    |        \         a|  |a           |
    |         \        a|  |a           |
    +----------+----+   +--+   +--------+
    |                          |
    |                          |
    |      +-------------------+

objects:
    p:
        name: Mysterious Present
        group: Presents
        visible: True
    a:
        name: Villager
        group: Villagers
        visible: True



triggers:
    H:
        - action: script
          script:
            - Strange Voice: Welcome!
            - Strange Voice: There have been 2 new monster attack(s) in the past 24 hour(s)
            - Strange Voice: Anyways, you're safe at home, so that means something, right?
            - Strange Voice: It'd be /really/ nice if someone did something about those monsters...
            - Strange Voice: And someone left you a present!
            - Strange Voice: Maybe it's a kitten?
            - Strange Voice: If you have further questions, do not hesitate to contact HARVON VILLAGE SUPPORT CENTER.
            - You: That was strange...
            - You: Well, better check out that present before heading out.
    A:
        - action: give
          item: Wooden Sword
          target: Player
        - action: remove
          target: Mysterious Present
        - action: script
          script:
            - Player: Woah, a wooden sword!
            - Player: Just what I've always wanted!
