# main-game level 2

map: |
    1                           -----+-------------------------------------------------------------------+----+
                                   /             s          hhhhh|        \             /    /     /     |     \
                                  +                         \    |   \     \           /33| /  \  /  \   |  /   \
                                  \    S                     +   |    \     \         / c \     \     \    /     \
                               +---+                    s    |   |     \ s   \       /----/   +-----------+  s    \
           +-------+           |  N=                         |ggg|      \     +-----+                      \       +
          /         \          +---+                         +   |  s    \                                  \     /
         +          a\            /       s                   \           \                                  |fff/
         |         aa +-------------------------------------------------------------------------------+      |  +
         |    +---+a       d   s                 s                   s                 s               \    s|   \
         /   /    |         d          s                    s                         s                 \    |    \
        /   /     |      +-------+---------------+---------------------------------------------------+   \   +     +
    +--+jjj/      |             /                 \             |                 \      s            \   \        |
    |     /       |            /  /+---------+     \   +-----+  /  +----+-------+  \                   \   \       |
    | @  /        |     s     /  //           \     \       /  /   |   / \    |  \  +             T     +   +      |
    +---+         +          /  //  /\         \     \     /          /    /      |ii                   |   |      |
                   \        /      /  \      s  \     \   +--------------------+ee+   +                 |  s|      +
                    \      +------+              \     \   s                  /    \ / \  s           s |   |     /
                     \      \        +------------+     |     +---------+    /      +   +---------------+   |    /
                      \      \                   /     /      |        /    /          /               /    +   /
                       \      \     +----+      /     /          /    /    /------+   /    +------    /        /
                        \      \   /  1c |     /   s /     +----+    /    /   s  /   /    / c2       /    +---+
                         \      \ /    1 |    /     /     /         /    /    / /   /    /222       /    / 4c /
                          \      +       |   /     /     /   s     /    /    /     /    /          /    /   4/
                           \      \     /   /     +-----+         /    /    +-----+    /          /       s /
                            \   s  \   /   /                     / s  /               /          /---------+
                             \      \ / s /       +-------------+    +---------------+     s    /
                              \          /            b                                        /
                               +--------------------------------------------------------------+

objects:
    B: #Miniboss
        name: Mini-Boss
        group: Mini-Bosses
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 1
              damage: 20
        attributes:
            health: 30
       
    M: # boss
        name: Boss
        group: Bosses
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 0
              damage: 40
        die:
            - action: give
              item: Magical Exit Key
              type: key
              attributes:
                  unlock: Exit Door
        attributes:
            health: 60

    c: #chest
        name: Chest
        group: Chests
        visible: True
        color: yellow

    s: #enemy spawner
        name: Goblin Spawner
        group: Goblin Spawners
        visible: False

    k: # goblin
        name: Goblin
        group: Goblins
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 3
              damage: 5
        attributes:
            health: 15

    S: # Boss spawner
        name: Boss Spawner
        group: Boss Spawners
        visible: False

    T: #Miniboss spawner
        name: Mini-Boss Spawner
        group: Mini-Boss Spawners
        visible: False

    =:
        name: Exit Door
        group: Doors
        visible: True
        color: magenta


triggers:
    j:
        - action: script
          script:
            - You: Wait, where am I?
            - You: This isn't my house!
    
    1: #chest 1
        - action: give
          actor: The chest
          item: Iron Sword
          type: weapon
          attributes:
               damage: 15

    2: #chest 2
        - action: give
          actor: The chest
          item: Bronze Sword
          type: weapon
          attributes:
               damage: 12

    3: #chest 3
        - action: give
          actor: The chest
          item: Something Strange
          type: weapon
          attributes:
               damage: 10

    4: #chest 4
        - action: give
          actor: The chest
          item: An orange
          type: weapon
          attributes:
               damage: 20
        - action: script
          script:
            - ???: An orange!
            - ???: The most powerful weapon in the free world!
            - ???: The gods must smile upon you, O strange one!

    a: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 

    b: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 

    d: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 

    e: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 
    
    f: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 

    g: #enemy trigger
        - action: spawn
          actor: group(Goblin Spawners)
          target: k 

    h: # boss trigger
        - action: spawn
          actor: group(Boss Spawners)
          target: M 

    i: # miniboss trigger
        - action: spawn
          actor: group(Mini-Boss Spawners)
          target: B

    N: # next level
        - action: load level
          level: level03
