# level 1 of main game

map: | 
    +-------------------------------------+
    |+-----------------------------------+|
    ||    H                  A           ||
    ||   @H                  AP          ||
    ||   HH                  A           ||
    |+------------------------+       +--+|
    ||                                   ||
    ||                                   ||
    |+-------+-----+     +--+     +------+|
    ||        \         a|  |a           ||
    ||         \        a|  |a           ||
    |+----------+----+   +--+   +--------+|
    ||                          |+-------+|
    ||                          ||     vc||
    ||      +-------------------+|     vv||
    ||      |                    |       ||
    ||      |    +---------------+      //
    ||      |    |                      ||
    ||      |    |        +-------------+|
    ||      +----+---   --+--------------+
    ||                    |
    ||                    |
    |+-------------+      +--
    +--------------|      =N  /
                   |      =N /
                   |      +-+
                   |      |
                   |      |
                   /      \
                  /        \
        /--------+          +-------------------------------------------------------------------------------------\\
       /                    |\------------------------------------------------------------------------------------\\\
      /     +---------------+\\-----------------------------------------------------------------------------------\\\\
     /      |         /      \\\\/////////////////////////////////////////////////////////////////////////////////\\\\\\\\\-+
     |      /     +  /   /    \\\\/////////                                                                           \\\\\\|
     |     /     /  /   /      \\\\//////      S                                                                     \\\\\\\|
     |    /     /  /   /        \\\\//////                                                                             \\\\\|
     |bbb+     /  /   / e        \\\\////                                                                           \\\\\\\\|
     |   |    /  +   +         |  \\\\/////                                                                        \\\\\\\\\|
     |   +   /   |   |         |   \\\/////                                                                           //////|
     |      /    |   |         |    \\//////                                                                         /////\/|
     |     /     |   |         |    e\\\////////////////////////////////////\/\\\\\\\\/\/////\\                    /////\///|
     |    /      |   |         |      \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\/\\\\/\\\\                  //////////|
     |   +       |   |   e     |       \\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\               /\/////////|
     |   |       +   |         |      hc\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\ zzzzzzzz /////////////|
     |   |           |         +-----------\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\      //////\//////\/|
     |   +-----------+---------------------+------------------------------------------------------------     +--------------|
     |   |            \\\\\\\\\\/\\\\\\\\\     sss                                                           ///////////////|
     |   |  +---+      \\\/\\\\\\\/\\\\\\\\    scs                                                  f       ///\////////////|
     |   |       \      \\\\\\\/\\\\\\\\\\\\   sss                  f                                      //////////\//////|
     |   +\       \      \\\\\\\\\\\\\/\\\\\\                                                             //\///////////////|
     |    \\       \      \\\\\/\\\\\\\\\\\\|                                                            ///////////////////|
     |     \\       \      \\\\\\\\\\\\/\\\\|                                                           /////////\//////////|
     |      \\       +      +----------------------------------------------------------------          ///////////////\//// |
     |       \\      |                                     d                                          ///////\///////////   |
     |        \\     |      +------------------------------+                                         //////\///////////// //|
     |         \\    |      |\\\\\\/\\\\\\\\\\/\\\\\\\\\\\/\\                                       /////////////\////// c /|
     |          \\   |      |\\/\\\\\\\\\/\\\\\\\\\\/\\\\\\\\\                                     //////////////////// gg//|
     |           +   |  e   |\\\\\\/\\\\\\\\\\\\\\/\\\\\\/\\\\+-----------------------------------+-----------------////   /|
     |               |      +--------------------------------------------------------------------------------------///    //+
     |     e         |                                                                                                   e//|
     +---------------+------------------------------------------------------------------------------------------------------+

objects:
    P:
        name: Mysterious Present
        group: Presents
        visible: True
        color: yellow
    a:
        name: Villager
        group: Villagers
        visible: True
        color: green
    c:
        name: Chest
        group: Chests
        visible: True
        color: yellow
    S:
        name: Boss Spawner
        group: Boss Spawners
        visible: False
    B:
        name: Boss
        group: Bosses
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 1
              damage: 25
        die:
            - action: script
              script:
                - Boss: You have proved a worthy challenger, hero.
                - Boss: "*cough* Ugh... *cough*"
                - Boss: "Here are the *cough* keys to get out of your *cough* house..."
                - Boss: "You *cough* earned them well..."
            - action: give
              item: Magical Exit Key
              type: key
              attributes:
                  unlock: Exit Door
            - action: script
              script:
                - You: Hmm... I wonder where the exit is?
        attributes:
            health: 40
    e:
        name: Spawner
        group: Weak Goblin Spawners
        visible: False
    f:
        name: Spawner
        group: Goblin Spawners
        visible: False
    E:
        name: Weak Goblin
        group: Goblins
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 2
              damage: 10
        attributes:
            health: 10
    F:
        name: Goblin
        group: Goblins
        visible: True
        color: red
        start:
            - action: attack
              target: Player
              speed: 2
              damage: 10
        attributes:
            health: 15
    =:
        name: Exit Door
        group: Doors
        visible: True
        color: magenta

triggers:
    H:
        - action: script
          script:
            - Strange Voice: Welcome!
            - Strange Voice: There have been 2 new monster attack(s) in the past 24 hour(s).
            - Strange Voice: Anyways, you're safe at home, so that means something, right?
            - Strange Voice: It'd be /really/ nice if someone did something about those monsters...
            - Strange Voice: And someone left you a present!
            - Strange Voice: Maybe it's a kitten?
            - Strange Voice: If you have further questions, do not hesitate to contact HARVON VILLAGE SUPPORT CENTER.
            - You: That was strange...
            - You: Well, better check out that present before heading out.
    A:
        - action: give
          actor: The mysterious present
          item: Wooden Sword
          type: weapon
          attributes:
              damage: 5
        - action: remove
          target: Mysterious Present
        - action: script
          script:
            - You: Woah, a wooden sword!
            - You: Just what I've always wanted!
    v:
        - action: give
          actor: The chest
          item: Health Potion
          type: potion
          attributes:
               health: 20
    h:
        - action: give
          actor: The chest
          item: Stale Minor Health Potion
          type: potion
          attributes:
               health: 5
    g:
        - action: give
          actor: The chest
          item: Bone
          type: weapon
          attributes:
               damage: 1
        - action: script
          script:
            - You: Well, that's disgusting.
            - You: I need to remember to be careful out here.
    s:
        - action: give
          actor: The chest
          item: Reinforced Wooden Sword
          type: weapon
          attributes:
               damage: 10
    b: # Spawn weak goblins
        - action: spawn
          actor: group(Weak Goblin Spawners)
          target: E
    d: # Spawn goblins
        - action: spawn
          actor: group(Goblin Spawners)
          target: F
    z: # Spawn boss
        - action: script
          script:
            - Boss: WHO DARES DISTURB MY SLUMBER!?!
        - action: spawn
          actor: group(Boss Spawners)
          target: B
        - action: script
          script:
            - You: Me, the valiant hero who just needs the keys to get out of his house!
            - Boss: That's the most deplorable act I can imagine!
            - Boss: You must DIE!!
    N: # Next level load trigger
        - action: load level
          level: level02
