# level 1 of main game

map: | 
    +-------------------------------------+
    |+-----------------------------------+|
    ||    H                  A           ||
    ||   @H                  Ap          ||
    ||   H                   A           ||
    |+------------------------+       +--+|
    ||                                   ||
    ||                                   ||
    |+-------+-----+     +--+     +------+|
    ||        \         a|  |a           ||
    ||         \        a|  |a           ||
    |+----------+----+   +--+   +--------+|
    ||                          |+-------+|
    ||                          ||     vc||
    ||      +-------------------+|     vv||
    ||      |                    |       ||
    ||      |    +---------------+      //
    ||      |    |                      ||
    ||      |    |        +-------------+|
    ||      +----+---   --+--------------+
    ||                    |
    ||                    |
    |+-------------+      +--
    +--------------|     L| N /
                   |     L| N/
                   |      +-+
                   |      |
                   |      |
                   /      \
                  /        \
        /--------+          +-------------------------------------------------------------------------------------\\
       /                    |\------------------------------------------------------------------------------------\\\
      /     +---------------+\\-----------------------------------------------------------------------------------\\\\
     /      |         /      \\\\/////////////////////////////////////////////////////////////////////////////////\\\\\\\\\-+
     |      /     +  /   /    \\\\/////////                                                                           \\\\\\|
     |     /     /  /   /      \\\\//////      S                                                                     \\\\\\\|
     |    /     /  /   /        \\\\//////                                                                             \\\\\|
     |bbb+     /  /   / e        \\\\////                                                                           \\\\\\\\|
     |   |    /  +   +         |  \\\\/////                                                                        \\\\\\\\\|
     |   +   /   |   |         |   \\\/////                                                                           //////|
     |      /    |   |         |    \\//////                                                                         /////\/|
     |     /     |   |         |    e\\\////////////////////////////////////\/\\\\\\\\/\/////\\                    /////\///|
     |    /      |   |         |      \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\/\\\\/\\\\                  //////////|
     |   +       |   |   e     |       \\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\               /\/////////|
     |   |       +   |         |      hc\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\ zzzzzzzz /////////////|
     |   |           |         +-----------\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\      //////\//////\/|
     |   +-----------+---------------------+------------------------------------------------------------     +--------------|
     |   |            \\\\\\\\\\/\\\\\\\\\      s                                                            ///////////////|
     |   |  +---+      \\\/\\\\\\\/\\\\\\\\    scs                                                  e       ///\////////////|
     |   |       \      \\\\\\\/\\\\\\\\\\\\    s                   e                                      //////////\//////|
     |   +\       \      \\\\\\\\\\\\\/\\\\\\                                                             //\///////////////|
     |    \\       \      \\\\\/\\\\\\\\\\\\|                                                            ///////////////////|
     |     \\       \      \\\\\\\\\\\\/\\\\|                                                           /////////\//////////|
     |      \\       +      +----------------------------------------------------------------          ///////////////\//// |
     |       \\      |                                     d                                          ///////\///////////   |
     |        \\     |      +------------------------------+                                         //////\///////////// //|
     |         \\    |      |\\\\\\/\\\\\\\\\\/\\\\\\\\\\\/\\                                       /////////////\////// c /|
     |          \\   |      |\\/\\\\\\\\\/\\\\\\\\\\/\\\\\\\\\                                     //////////////////// gg//|
     |           +   |  e   |\\\\\\/\\\\\\\\\\\\\\/\\\\\\/\\\\+-----------------------------------+-----------------////   /|
     |               |      +--------------------------------------------------------------------------------------///    //+
     |     e         |                                                                                                   e//|
     +---------------+------------------------------------------------------------------------------------------------------+

objects:
    p:
        name: Mysterious Present
        group: Presents
        visible: True
    a:
        name: Villager
        group: Villagers
        visible: True
    c:
        name: Chest
        group: Chests
        visible: True
    S:
        name: Boss Spawner
        group: Boss Spawners
        visible: False
    B:
        name: Boss
        group: Bosses
        visible: True
        color: red
        start:
            - action: attack
              target: Player
        attributes:
            health: 30
            defense: 5
            speed: 2
            attack: 6
    e:
        name: Spawner
        group: Weak Goblin Spawners
        visible: False
    E:
        name: Weak Goblin
        group: Goblins
        visible: True
        color: red
        start:
            - action: attack
              target: Player
        attributes:
            health: 10
            defense: 2
            speed: 1
            attack: 2


triggers:
    H:
        - action: script
          script:
            - Strange Voice: Welcome!
            - Strange Voice: There have been 2 new monster attack(s) in the past 24 hour(s)
            - Strange Voice: Anyways, you're safe at home, so that means something, right?
            - Strange Voice: It'd be /really/ nice if someone did something about those monsters...
            - Strange Voice: And someone left you a present!
            - Strange Voice: Maybe it's a kitten?
            - Strange Voice: If you have further questions, do not hesitate to contact HARVON VILLAGE SUPPORT CENTER.
            - You: That was strange...
            - You: Well, better check out that present before heading out.
    A:
        - action: give
          actor: The mysterious present
          item: Wooden Sword
          type: weapon
          attributes:
              damage: 5
        - action: remove
          target: Mysterious Present
        - action: script
          script:
            - You: Woah, a wooden sword!
            - You: Just what I've always wanted!
    v:
        - action: give
          actor: chest
          item: Health Potion
          type: potion
          attributes:
               health: 4
    h:
        - action: give
          actor: chest
          item: Stale Minor Health Potion
          type: potion
          attributes:
               health: 1
    g:
        - action: give
          actor: chest
          item: Bone
          type: weapon
          attributes:
               damage: 1
        - action: script
          script:
            - You: Well, that's disgusting.
            - You: I need to remember to be careful out here.
    s:
        - action: give
          actor: chest
          item: Reinforced wooden sword
          type: weapon
          attributes:
               damage: 6
    b: # Spawn weak goblins
        - action: spawn
          actor: group(Weak Goblin spawners)
          target: E
    d: # Spawn weak goblins
        - action: spawn
          actor: group(Weak Goblin spawners)
          target: E
    z: # Spawn boss
        - action: script
          script:
            - Boss: WHO DARES DISTURB MY SLUMBER!?!
            - You: Me, the valiant hero who just needs the keys to get out of his house!
            - Boss: That's the most deplorable act I can imagine!
            - Boss: You must DIE!!
        - action: spawn
          actor: group(Boss spawners)
          target: B
    N: # Next level load trigger
        - action: load level
          level: level02
    L: # Door key stuff
        - action: script
          script:
            - Ben hasn't implemented keys and stuff yet, so this is a reminder.
            - Or maybe it's just a joke so we don't have to write more than one map.
            - Who can know for sure?
